"""Scheduled, calendar-driven video PRODUCTION only -- publishing is
NEVER part of this script, by construction. Notice the import list right
below this docstring: nothing from `webui` or `app.departments.growth.
publisher` is imported here, anywhere -- not directly, not transitively
through anything this file imports. `app.pipeline.default_pipeline`
(and everything IT imports) never imports `publisher` either (verified:
`grep -rln "from app.departments.growth import publisher" app/ webui/`
returns exactly one file, `webui/Main.py`). A video generated by this
script is written to storage/tasks/<id>/ and shows up in the webui's
"Geçmiş Üretimler" page like any other project -- a human still has to
open it and click Publish for anything to ever reach a real platform.
See test/services/test_scheduled_generate_safety.py, which parses this
file's AST and fails the build if that ever stops being true.

Reads resource/content_calendar/<niche>_calendar.yaml (see
resource/content_calendar/README.md for the schema), picks the next
"planned" entry for the requested --kind (long|short), runs it through
the exact same app.pipeline.default_pipeline.run_pipeline() the webui
uses -- with the video source FORCED to free stock footage (Pexels).
On success, marks the calendar entry "generated" and writes the YAML
back. On failure, logs and exits non-zero WITHOUT touching the calendar
entry, so the next scheduled run retries the same topic (no automatic
retry within a single run -- see PROGRESS.md's "no silent fallback for
a paid action" precedent this follows).

Runs equally well as a systemd oneshot service (see
deploy/systemd/documentary-scheduled-{long,short}.service) or by hand,
today, without waiting for the real weekly schedule:
    .venv/bin/python scripts/scheduled_generate.py --kind short
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

import yaml
from loguru import logger

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from app.config import config  # noqa: E402
from app.config.profile_dimensions import Format, Pacing  # noqa: E402
from app.pipeline import default_pipeline  # noqa: E402

CALENDAR_PATH = ROOT_DIR / "resource" / "content_calendar" / "zihin_davranis_calendar.yaml"
LOG_PATH = ROOT_DIR / "resource" / "content_calendar" / "scheduled_generate.log"

# "Haftalık Otomatik Üretim" planı (kullanıcı onaylı, MADDE 4): otomatik
# üretimde GERÇEK PARA HARCAYAN bir video aşaması KESİNLİKLE olmayacak.
# Bilinçli olarak hiçbir YAML alanı/CLI argümanı bunu override edemez --
# takvim şemasında böyle bir alan hiç YOK.
FORCED_VIDEO_SOURCE = "pexels"

# Niş "educational" formatta -- MADDE 4'ün aynısı, sabit/zorlanmış.
FORCED_FORMAT = Format.educational

_KIND_TO_PACING = {"long": Pacing.extended, "short": Pacing.short}
_KIND_TO_CALENDAR_KEY = {"long": "long_form", "short": "shorts"}
# GÖREV 1 (gece oturumu) ile aynı gerekçe: extended/"belgesel" içerik
# 16:9, Shorts-tarzı short pacing 9:16.
_KIND_TO_ASPECT = {"long": "16:9", "short": "9:16"}


def _log(message: str) -> None:
    line = f"{datetime.now(timezone.utc).isoformat()} {message}"
    logger.info(line)
    with open(LOG_PATH, "a", encoding="utf-8") as f:
        f.write(line + "\n")


def _load_calendar() -> dict:
    with open(CALENDAR_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _save_calendar(data: dict) -> None:
    with open(CALENDAR_PATH, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False)


def _next_planned_entry(calendar: dict, kind: str) -> dict | None:
    entries = calendar.get(_KIND_TO_CALENDAR_KEY[kind]) or []
    for entry in entries:
        if entry.get("status") == "planned":
            return entry
    return None


def run(kind: str) -> int:
    if kind not in _KIND_TO_PACING:
        _log(f"ERROR: unknown --kind {kind!r}")
        return 2

    calendar = _load_calendar()
    entry = _next_planned_entry(calendar, kind)
    if entry is None:
        _log(
            f"SKIP: no planned entries left for kind={kind} -- "
            f"add more to {CALENDAR_PATH.name}"
        )
        return 0

    topic = entry.get("topic", "")
    topic_category = entry.get("topic_category") or None
    tone = entry.get("tone") or None
    language = calendar.get("language", "tr")
    voice_name = config.ui.get("voice_name", "")
    project_id = f"sched-{kind}-{uuid4()}"

    _log(f"START: kind={kind} project_id={project_id} topic={topic!r}")
    try:
        default_pipeline.run_pipeline(
            project_id=project_id,
            topic=topic,
            language=language,
            topic_category_override=topic_category,
            tone=tone,
            format=FORCED_FORMAT,
            pacing=_KIND_TO_PACING[kind],
            voice_name=voice_name,
            video_source=FORCED_VIDEO_SOURCE,
            video_aspect=_KIND_TO_ASPECT[kind],
        )
    except Exception as e:
        _log(f"FAILED: kind={kind} project_id={project_id} topic={topic!r} error={e}")
        return 1

    entry["status"] = "generated"
    _save_calendar(calendar)
    _log(f"OK: kind={kind} project_id={project_id} topic={topic!r}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", required=True, choices=["long", "short"])
    args = parser.parse_args()
    return run(args.kind)


if __name__ == "__main__":
    # Savunma derinliği (bkz. dosya başı docstring): publisher hiç
    # import edilmemiş olmalı -- import edilseydi bile burada, gerçek
    # bir üretim başlamadan ÖNCE çökerdi.
    assert "app.departments.growth.publisher" not in sys.modules, (
        "scheduled_generate.py must never import app.departments.growth.publisher"
    )
    sys.exit(main())
